services:
  - type: web
    name: quiz-app
    env: java
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/quiz-0.0.1-SNAPSHOT.jar"
    branch: master
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DB_HOST
        value: your-db-host.onrender.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-username
      - key: DB_PASSWORD
        value: your-db-password
