services:
  - type: web
    name: quiz-app
    env: java
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/quiz-0.0.1-SNAPSHOT.jar"
    branch: master
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DB_HOST
        value: dpg-cvu7u0s9c44c73ftbbgg-a
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: quiz_ruq7
      - key: DB_USERNAME
        value: quiz_ruq7_user
      - key: DB_PASSWORD
        value: nhrEGc8nyvcu4LBEEvR7fnykOyHYxCr7
